config/routes.rb
MyTreeApp::Application.routes.draw do
  resources :my_js_trees

  get '/trees', :to => 'my_js_trees#jstree'
  get '/treedata', :to => 'my_js_trees#jstreedata'
    

end

app/models/my_js_tree.rb
class MyJsTree < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_js_trees_controller.rb
class MyJsTreesController < ApplicationController
  before_action :set_my_js_tree, only: [:show, :edit, :update, :destroy]

  # GET /my_js_trees
  # GET /my_js_trees.json
    
  def jstreedata
      
      @all_ous = MyJsTree.all
      
      respond_to do |format|
          format.json
      end
  end
      
    
  def jstree
    respond_to do |format|
      format.html
    end
  end
      
      
  def index
    @my_js_trees = MyJsTree.all
  end

  # GET /my_js_trees/1
  # GET /my_js_trees/1.json
  def show
  end

  # GET /my_js_trees/new
  def new
    @my_js_tree = MyJsTree.new
  end

  # GET /my_js_trees/1/edit
  def edit
  end

  # POST /my_js_trees
  # POST /my_js_trees.json
  def create
    @my_js_tree = MyJsTree.new(my_js_tree_params)

    respond_to do |format|
      if @my_js_tree.save
        format.html { redirect_to @my_js_tree, notice: 'My js tree was successfully created.' }
        format.json { render action: 'show', status: :created, location: @my_js_tree }
      else
        format.html { render action: 'new' }
        format.json { render json: @my_js_tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_js_trees/1
  # PATCH/PUT /my_js_trees/1.json
  def update
    respond_to do |format|
      if @my_js_tree.update(my_js_tree_params)
        format.html { redirect_to @my_js_tree, notice: 'My js tree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @my_js_tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_js_trees/1
  # DELETE /my_js_trees/1.json
  def destroy
    @my_js_tree.destroy
    respond_to do |format|
      format.html { redirect_to my_js_trees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_js_tree
      @my_js_tree = MyJsTree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_js_tree_params
      params.require(:my_js_tree).permit(:OUName, :Parent_ID)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_js_trees_helper.rb
module MyJsTreesHelper
  #Cycles round each root node
  def get_children_for_root(all_ous)
      
    boo = {}
      
      boo = add_children(1, all_ous)
      
    return boo
  end
    
  def add_children(parent_id, all_ous)
      
      data = {:data => (get_OU_Name(parent_id))}
      data[:children] = children = []
      
      #cycle round all the ous and check if they are child of the parent_id
      all_ous.each_with_index do |ou, index|
          
          if(parent_id == ou.Parent_ID)
              
              children << add_children(ou.id, all_ous)
              
          end
      end
      #clear up empty children
      if children.empty?
          data.delete(:children)
      end
      return data
  end
    
  def get_OU_Name(id)
      @ou = MyJsTree.find(id)
      
      return @ou.OUName
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyTreeApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_js_trees/_form.html.erb
<%= form_for(@my_js_tree) do |f| %>
  <% if @my_js_tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_js_tree.errors.count, "error") %> prohibited this my_js_tree from being saved:</h2>

      <ul>
      <% @my_js_tree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :OUName %><br>
    <%= f.text_field :OUName %>
  </div>
  <div class="field">
    <%= f.label :Parent_ID %><br>
    <%= f.number_field :Parent_ID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_js_trees/edit.html.erb
<h1>Editing my_js_tree</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_js_tree %> |
<%= link_to 'Back', my_js_trees_path %>

app/views/my_js_trees/index.html.erb
<h1>Passport Parking - Programming Challenge</h1>

<table>
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Parent Id</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @my_js_trees.each do |my_js_tree| %>
      <tr>
        <td><%= my_js_tree.OUName %></td>
        <td><%= my_js_tree.Parent_ID %></td>
        <td><%= link_to 'Show', my_js_tree %></td>
        <td><%= link_to 'Edit', edit_my_js_tree_path(my_js_tree) %></td>
        <td><%= link_to 'Destroy', my_js_tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My js tree', new_my_js_tree_path %>

app/views/my_js_trees/jstree.html.erb
<script>
$(document).ready(function(){
  $("#treeViewDiv").jstree({
    core : { "animation" : 100},
    themes : { "theme" : "classic", "icons" : true, "dots": false },
    "json_data" : {
        "ajax" : {
                  "url" : "/treedata.json",
                    "data" : function (m) {
                            return { id : m.attr ? m.attr("id") : 0 };
                    }
        }
    },
    plugins : ["themes", "json_data", "ui", "crrm" ]
      
  }).bind("select_node.jstree", function(e, data)
  {
    if(jQuery.data(data.rslt.obj[0], "href"))
    {
        window.location=jQuery.data(data.rslt.obj[0], "href");
    }
    else
    {
        alert("No href defined for this element");
    }
  })
});
</script>

<p><b>Tree View</b></p>

<div id="treeViewDiv"></div>

app/views/my_js_trees/jstreedata.json.erb
<%
    
params = {}
params = get_children_for_root(@all_ous)
    
%>
<%=
    #display the anser
    params.to_json.html_safe
%>

app/views/my_js_trees/new.html.erb
<h1>New my_js_tree</h1>

<%= render 'form' %>

<%= link_to 'Back', my_js_trees_path %>

app/views/my_js_trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category Name:</strong>
  <%= @my_js_tree.OUName %>
</p>

<p>
  <strong>Parent Id:</strong>
  <%= @my_js_tree.Parent_ID %>
</p>

<%= link_to 'Edit', edit_my_js_tree_path(@my_js_tree) %> |
<%= link_to 'Back', my_js_trees_path %>